#!/usr/bin/env node

var program = require('commander')
  , colors = require('colors')
  , AWS = require('aws-sdk')
  , Q = require('q');

program
  .usage('show')
  .description('list AWS CodeCommit repositories')
  .action(function() {
    var deferred = Q.defer();
    var codecommit = new AWS.CodeCommit({region:'us-east-1'});

    console.log('Retrieving repo...');
    repoParams = {};
    repoParams.repositoryNames = ['.'];
    codecommit.batchGetRepositories( repoParams, function(err, data) {
      if ( err ) {
        console.error( err );
        deferred.reject( err );
      } else {
        console.dir( data );
      }
    } );

    return deferred.promise;
  });

program.parse(process.argv);
