#!/usr/bin/env node

var program = require('commander')
  , colors = require('colors');

program
  .version('0.0.1')
  .command('migrate [options] <repo-url> [repo-description]', 'migrate GitHub repo to AWS CodeCommit')
  .command('show', 'list AWS CodeCommit repositories')
  .parse(process.argv);
